name: Continuous integration
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'sbt'
      - name: Compile, test
        run: sbt clean coverage test coverageReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
