name: Scala Steward
on:
  # This workflow will launch at 00:00 every day
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.SCALA_STEWARD_GITHUB_TOKEN }}
          author-email: 74173353+toolsplus-scala-steward@users.noreply.github.com
